/*
 * SPDX-FileCopyrightText: 2026 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "bsp_board.h"

#ifdef BSP_LCDC_USING_DPI
    #define LCD_RESET_PIN           (21)         // GPIO_A21
#elif defined(BSP_LCDC_USING_DBI)
    #define LCD_RESET_PIN           (42)         // GPIO_A42
#else
    #define LCD_RESET_PIN           (43)         // GPIO_A43
#endif /* BSP_LCDC_USING_DPI */
#define TP_RESET                (7)          // GPIO_A07

#define EPD_GMODE_PIN           (54)         // GPIO_A54

#define EPD_VDD33_EN            (52)         // GPIO_A52 
#define CTP_VDD33_EN            (53)         // GPIO_A53 


extern void BSP_GPIO_Set(int pin, int val, int is_porta);

void BSP_LCD_Reset(uint8_t high1_low0)
{
    BSP_GPIO_Set(LCD_RESET_PIN, high1_low0, 1);
}


void BSP_LCD_PowerDown(void)
{
    BSP_LCD_Reset(0);
}

void BSP_LCD_PowerUp(void)
{
#ifdef BSP_LCDC_USING_DPI
    HAL_PIN_Set(PAD_PA20, LCDC1_DPI_VSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA24, LCDC1_DPI_R0,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA25, LCDC1_DPI_DE,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA26, LCDC1_DPI_R1,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA27, LCDC1_DPI_HSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA28, LCDC1_DPI_R2,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA29, LCDC1_DPI_CLK,   PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA30, LCDC1_DPI_R3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA31, LCDC1_DPI_B7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA32, LCDC1_DPI_R4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA33, LCDC1_DPI_B6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA37, LCDC1_DPI_B2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA38, LCDC1_DPI_R5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA39, LCDC1_DPI_B1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA40, LCDC1_DPI_R6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA41, LCDC1_DPI_B0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA42, LCDC1_DPI_R7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA43, LCDC1_DPI_G7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_DPI_G0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_DPI_G6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA46, LCDC1_DPI_G1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_DPI_G5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_DPI_G2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA49, LCDC1_DPI_G4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_DPI_G3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA52, LCDC1_DPI_B3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA53, LCDC1_DPI_B4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA54, LCDC1_DPI_B5, PIN_NOPULL, 1);

    HAL_PIN_Set(PAD_PA11, GPTIM1_CH4, PIN_NOPULL, 1);   // LCDC1_BL_PWM_CTRL, LCD backlight PWM

#elif defined(BSP_LCDC_USING_DBI)
    HAL_PIN_Set(PAD_PA24, LCDC1_8080_TE,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA25, LCDC1_8080_DIO15, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA26, LCDC1_8080_CS,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA27, LCDC1_8080_DIO14, PIN_NOPULL, 1);
    // TODO:
    HAL_PIN_Set(PAD_PA28, LCDC1_8080_DC,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA29, LCDC1_8080_DIO13, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA30, LCDC1_8080_WR,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA31, LCDC1_8080_DIO12, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA32, LCDC1_8080_RD,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA33, LCDC1_8080_DIO11, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA37, LCDC1_8080_DIO10, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA39, LCDC1_8080_DIO9, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA41, LCDC1_8080_DIO8, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA43, LCDC1_8080_DIO7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_8080_DIO0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_8080_DIO6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA46, LCDC1_8080_DIO1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_8080_DIO5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_8080_DIO2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA49, LCDC1_8080_DIO4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_8080_DIO3, PIN_NOPULL, 1);

    HAL_PIN_Set(PAD_PA20, GPTIM1_CH4, PIN_NOPULL, 1);   // LCDC1_BL_PWM_CTRL, LCD backlight PWM

    //SPI_DI： PA38, SPI_DO: PA40

#elif defined(BSP_LCDC_USING_EPD_8BIT)
    HAL_PIN_Set(PAD_PA25, LCDC1_TCON_GDSP,   PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA27, LCDC1_TCON_GDCLK,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA28, LCDC1_TCON_SDCLK,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA29, LCDC1_TCON_SDAT15, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA30, LCDC1_TCON_SDLE,   PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA31, LCDC1_TCON_SDAT14, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA32, LCDC1_TCON_SDOE,   PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA33, LCDC1_TCON_SDAT13, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA37, LCDC1_TCON_SDAT12, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA38, LCDC1_TCON_SDSTL,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA39, LCDC1_TCON_SDAT11, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA40, LCDC1_TCON_SDAT0,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA41, LCDC1_TCON_SDAT10, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA42, LCDC1_TCON_SDAT1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA43, LCDC1_TCON_SDAT9, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_TCON_SDAT2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_TCON_SDAT8, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA46, LCDC1_TCON_SDAT3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_TCON_SDAT7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_TCON_SDAT4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA49, LCDC1_TCON_SDAT6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_TCON_SDAT5, PIN_NOPULL, 1);

    HAL_PIN_Set(PAD_PA54, GPIO_A5, PIN_PULLUP, 1);  //GMODE

    HAL_PIN_Set(PAD_PA11, GPTIM1_CH4, PIN_NOPULL, 1);   // LCDC1_BL_PWM_CTRL, LCD backlight PWM

#elif defined(BSP_LCDC_USING_QADSPI)
    HAL_PIN_Set(PAD_PA42, LCDC1_MATRIX_SPI_DIO3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_MATRIX_SPI_DIO2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA46, LCDC1_MATRIX_SPI_DIO1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_MATRIX_SPI_TE,   PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_MATRIX_SPI_DIO0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA49, LCDC1_MATRIX_SPI_CS,   PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_MATRIX_SPI_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set_DS0(PAD_PA50, 1, 1);
    HAL_PIN_Set_DS1(PAD_PA50, 1, 0);

    HAL_PIN_Set(PAD_PA45, GPTIM1_CH4, PIN_NOPULL, 1);   // LCDC1_BL_PWM_CTRL, LCD backlight PWM

    HAL_PIN_Set(PAD_PA43, GPIO_A43, PIN_NOPULL, 1); //LCD RESET PIN
#endif /* BSP_LCDC_USING_QADSPI */
}

void BSP_LCD_GMODE_Set(uint8_t high1_low0)
{
    BSP_GPIO_Set(EPD_GMODE_PIN, high1_low0, 1);
}


void BSP_TP_PowerUp(void)
{
    HAL_PIN_Set(PAD_PA00 + TP_RESET, GPIO_A0 + TP_RESET, PIN_NOPULL, 1);
    BSP_GPIO_Set(TP_RESET,  1, 1);

#ifdef BOARD_TP_I2C_PINMAP_0
    HAL_PIN_Set(PAD_PA22, I2C1_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA23, I2C1_SCL, PIN_PULLUP, 1);
#elif BOARD_TP_I2C_PINMAP_1
    HAL_PIN_Set(PAD_PA51, I2C1_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA57, I2C1_SCL, PIN_PULLUP, 1);
#endif /* BOARD_TP_I2C_PINMAP_0 */

}

void BSP_TP_PowerDown(void)
{
    BSP_GPIO_Set(TP_RESET,  0, 1);
}

void BSP_TP_Reset(uint8_t high1_low0)
{
    BSP_GPIO_Set(TP_RESET, high1_low0, 1);
}

