/*
 * SPDX-FileCopyrightText: 2019-2022 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "bsp_board.h"

void BSP_PIN_Init(void)
{
#ifdef SOC_BF0_HCPU
    // HCPU pins

    // SDIO1
#ifdef BSP_USING_SDMMC1
    HAL_PIN_Set(PAD_PA08, SD1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA09, SD1_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA10, SD1_DIO0, PIN_PULLUP, 1);
#endif /* BSP_USING_SDMMC1 */

#ifdef BSP_USING_SDMMC2
    HAL_PIN_Set(PAD_PA02, SD2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA03, SD2_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA04, SD2_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA05, SD2_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA00, SD2_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA01, SD2_DIO3, PIN_PULLUP, 1);
#endif /* BSP_USING_SDMMC2 */


#if defined(BSP_USING_DCMI)
    // Digital Camera Interface

#ifdef BOARD_DVP_PINMAP_0
    HAL_PIN_Set(PAD_PA00, DCMI_VSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA01, DCMI_HSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA003, DCMI_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA04, DCMI_DI0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA05, DCMI_DI3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA07, DCMI_DI5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA08, DCMI_DI1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA09, DCMI_DI2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA10, DCMI_DI4, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA35, DCMI_DI7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA36, DCMI_DI6, PIN_NOPULL, 1);

    HAL_PIN_Set(PAD_PA02, GPTIM2_CH1, PIN_PULLUP, 1); // mclk output
#elif defined(BOARD_DVP_PINMAP_1)
    HAL_PIN_Set(PAD_PA26, DCMI_VSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA27, DCMI_HSYNC, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA29, DCMI_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA30, DCMI_DI0, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA31, DCMI_DI3, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA32, DCMI_DI1, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA33, DCMI_DI2, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA37, DCMI_DI7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA38, DCMI_DI6, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA39, DCMI_DI5, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA40, DCMI_DI4, PIN_NOPULL, 1);

    HAL_PIN_Set(PAD_PA28, GPTIM2_CH1, PIN_PULLUP, 1); // mclk output
#endif /* BOARD_DVP_PINMAP_0 */

#endif /* BSP_USING_DCMI */

#ifdef BSP_USING_PDM1
    HAL_PIN_Set(PAD_PA20, PDM1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA21, PDM1_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM1 */

#ifdef BSP_USING_PDM2
    HAL_PIN_Set(PAD_PA52, PDM2_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA53, PDM2_DATA, PIN_PULLDOWN, 1);
#endif /* BSP_USING_PDM2 */

#endif  /* SOC_BF0_HCPU */


}

