import os
import rtconfig
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path =  [cwd]

if GetDepend('CFG_BOOTROM'):
    SrcRemove(src, 'board_psram.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')

