#ifndef __SECU2_H
#define __SECU2_H

typedef struct
{
    __IO uint32_t SECU_CTRL;
    __IO uint32_t IRQ_STAT0;
    __IO uint32_t IRQ_STAT1;
    __IO uint32_t IRQ_STAT2;
    __IO uint32_t IRQ_CFG0;
    __IO uint32_t IRQ_CFG1;
    __IO uint32_t IRQ_CFG2;
    __IO uint32_t LPMST_ATTR_CFG;
    __IO uint32_t LPSLV_ATTR_CFG0;
    __IO uint32_t LPSLV_ATTR_CFG1;
    __IO uint32_t RAM0_R0_CFG0;
    __IO uint32_t RAM0_R0_CFG1;
    __IO uint32_t RAM0_R1_CFG0;
    __IO uint32_t RAM0_R1_CFG1;
    __IO uint32_t RAM0_RW_CFG;
    __IO uint32_t RAM1_R0_CFG0;
    __IO uint32_t RAM1_R0_CFG1;
    __IO uint32_t RAM1_R1_CFG0;
    __IO uint32_t RAM1_R1_CFG1;
    __IO uint32_t RAM1_RW_CFG;
} SECU2_TypeDef;


/**************** Bit definition for SECU2_SECU_CTRL register *****************/
#define SECU2_SECU_CTRL_LPMST_LOCK_Pos  (0U)
#define SECU2_SECU_CTRL_LPMST_LOCK_Msk  (0x1UL << SECU2_SECU_CTRL_LPMST_LOCK_Pos)
#define SECU2_SECU_CTRL_LPMST_LOCK      SECU2_SECU_CTRL_LPMST_LOCK_Msk
#define SECU2_SECU_CTRL_LPSLV_LOCK_Pos  (1U)
#define SECU2_SECU_CTRL_LPSLV_LOCK_Msk  (0x1UL << SECU2_SECU_CTRL_LPSLV_LOCK_Pos)
#define SECU2_SECU_CTRL_LPSLV_LOCK      SECU2_SECU_CTRL_LPSLV_LOCK_Msk
#define SECU2_SECU_CTRL_RAM_LOCK_Pos    (2U)
#define SECU2_SECU_CTRL_RAM_LOCK_Msk    (0x1UL << SECU2_SECU_CTRL_RAM_LOCK_Pos)
#define SECU2_SECU_CTRL_RAM_LOCK        SECU2_SECU_CTRL_RAM_LOCK_Msk
#define SECU2_SECU_CTRL_LPMST_ATTR_UPDATE_Pos  (8U)
#define SECU2_SECU_CTRL_LPMST_ATTR_UPDATE_Msk  (0x1UL << SECU2_SECU_CTRL_LPMST_ATTR_UPDATE_Pos)
#define SECU2_SECU_CTRL_LPMST_ATTR_UPDATE  SECU2_SECU_CTRL_LPMST_ATTR_UPDATE_Msk

/**************** Bit definition for SECU2_IRQ_STAT0 register *****************/
#define SECU2_IRQ_STAT0_ILL_RAM0_PRIV_W_Pos  (0U)
#define SECU2_IRQ_STAT0_ILL_RAM0_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM0_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM0_PRIV_W  SECU2_IRQ_STAT0_ILL_RAM0_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_RAM0_PRIV_R_Pos  (1U)
#define SECU2_IRQ_STAT0_ILL_RAM0_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM0_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM0_PRIV_R  SECU2_IRQ_STAT0_ILL_RAM0_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_RAM0_SEC_W_Pos  (2U)
#define SECU2_IRQ_STAT0_ILL_RAM0_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM0_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM0_SEC_W  SECU2_IRQ_STAT0_ILL_RAM0_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_RAM0_SEC_R_Pos  (3U)
#define SECU2_IRQ_STAT0_ILL_RAM0_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM0_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM0_SEC_R  SECU2_IRQ_STAT0_ILL_RAM0_SEC_R_Msk
#define SECU2_IRQ_STAT0_ILL_RAM1_PRIV_W_Pos  (4U)
#define SECU2_IRQ_STAT0_ILL_RAM1_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM1_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM1_PRIV_W  SECU2_IRQ_STAT0_ILL_RAM1_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_RAM1_PRIV_R_Pos  (5U)
#define SECU2_IRQ_STAT0_ILL_RAM1_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM1_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM1_PRIV_R  SECU2_IRQ_STAT0_ILL_RAM1_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_RAM1_SEC_W_Pos  (6U)
#define SECU2_IRQ_STAT0_ILL_RAM1_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM1_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM1_SEC_W  SECU2_IRQ_STAT0_ILL_RAM1_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_RAM1_SEC_R_Pos  (7U)
#define SECU2_IRQ_STAT0_ILL_RAM1_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RAM1_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_RAM1_SEC_R  SECU2_IRQ_STAT0_ILL_RAM1_SEC_R_Msk
#define SECU2_IRQ_STAT0_ILL_CRC2_PRIV_W_Pos  (8U)
#define SECU2_IRQ_STAT0_ILL_CRC2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_CRC2_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_CRC2_PRIV_W  SECU2_IRQ_STAT0_ILL_CRC2_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_CRC2_PRIV_R_Pos  (9U)
#define SECU2_IRQ_STAT0_ILL_CRC2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_CRC2_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_CRC2_PRIV_R  SECU2_IRQ_STAT0_ILL_CRC2_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_CRC2_SEC_W_Pos  (10U)
#define SECU2_IRQ_STAT0_ILL_CRC2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_CRC2_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_CRC2_SEC_W  SECU2_IRQ_STAT0_ILL_CRC2_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_CRC2_SEC_R_Pos  (11U)
#define SECU2_IRQ_STAT0_ILL_CRC2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_CRC2_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_CRC2_SEC_R  SECU2_IRQ_STAT0_ILL_CRC2_SEC_R_Msk
#define SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_W_Pos  (12U)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_W  SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_R_Pos  (13U)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_R  SECU2_IRQ_STAT0_ILL_BT_MAC_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_W_Pos  (14U)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_W  SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_R_Pos  (15U)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_R  SECU2_IRQ_STAT0_ILL_BT_MAC_SEC_R_Msk
#define SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_W_Pos  (16U)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_W  SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_R_Pos  (17U)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_R  SECU2_IRQ_STAT0_ILL_BT_PHY_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_W_Pos  (18U)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_W  SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_R_Pos  (19U)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_R  SECU2_IRQ_STAT0_ILL_BT_PHY_SEC_R_Msk
#define SECU2_IRQ_STAT0_ILL_RFC_PRIV_W_Pos  (20U)
#define SECU2_IRQ_STAT0_ILL_RFC_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RFC_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_RFC_PRIV_W  SECU2_IRQ_STAT0_ILL_RFC_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_RFC_PRIV_R_Pos  (21U)
#define SECU2_IRQ_STAT0_ILL_RFC_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RFC_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_RFC_PRIV_R  SECU2_IRQ_STAT0_ILL_RFC_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_RFC_SEC_W_Pos  (22U)
#define SECU2_IRQ_STAT0_ILL_RFC_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RFC_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_RFC_SEC_W   SECU2_IRQ_STAT0_ILL_RFC_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_RFC_SEC_R_Pos  (23U)
#define SECU2_IRQ_STAT0_ILL_RFC_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_RFC_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_RFC_SEC_R   SECU2_IRQ_STAT0_ILL_RFC_SEC_R_Msk
#define SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_W_Pos  (24U)
#define SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_W_Pos)
#define SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_W  SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_W_Msk
#define SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_R_Pos  (25U)
#define SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_R_Pos)
#define SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_R  SECU2_IRQ_STAT0_ILL_GPIO2_PRIV_R_Msk
#define SECU2_IRQ_STAT0_ILL_GPIO2_SEC_W_Pos  (26U)
#define SECU2_IRQ_STAT0_ILL_GPIO2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_GPIO2_SEC_W_Pos)
#define SECU2_IRQ_STAT0_ILL_GPIO2_SEC_W  SECU2_IRQ_STAT0_ILL_GPIO2_SEC_W_Msk
#define SECU2_IRQ_STAT0_ILL_GPIO2_SEC_R_Pos  (27U)
#define SECU2_IRQ_STAT0_ILL_GPIO2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT0_ILL_GPIO2_SEC_R_Pos)
#define SECU2_IRQ_STAT0_ILL_GPIO2_SEC_R  SECU2_IRQ_STAT0_ILL_GPIO2_SEC_R_Msk

/**************** Bit definition for SECU2_IRQ_STAT1 register *****************/
#define SECU2_IRQ_STAT1_ILL_SECU2_PRIV_W_Pos  (0U)
#define SECU2_IRQ_STAT1_ILL_SECU2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_SECU2_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_SECU2_PRIV_W  SECU2_IRQ_STAT1_ILL_SECU2_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_SECU2_PRIV_R_Pos  (1U)
#define SECU2_IRQ_STAT1_ILL_SECU2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_SECU2_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_SECU2_PRIV_R  SECU2_IRQ_STAT1_ILL_SECU2_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_SECU2_SEC_W_Pos  (2U)
#define SECU2_IRQ_STAT1_ILL_SECU2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_SECU2_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_SECU2_SEC_W  SECU2_IRQ_STAT1_ILL_SECU2_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_SECU2_SEC_R_Pos  (3U)
#define SECU2_IRQ_STAT1_ILL_SECU2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_SECU2_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_SECU2_SEC_R  SECU2_IRQ_STAT1_ILL_SECU2_SEC_R_Msk
#define SECU2_IRQ_STAT1_ILL_USART5_PRIV_W_Pos  (4U)
#define SECU2_IRQ_STAT1_ILL_USART5_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_USART5_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_USART5_PRIV_W  SECU2_IRQ_STAT1_ILL_USART5_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_USART5_PRIV_R_Pos  (5U)
#define SECU2_IRQ_STAT1_ILL_USART5_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_USART5_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_USART5_PRIV_R  SECU2_IRQ_STAT1_ILL_USART5_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_USART5_SEC_W_Pos  (6U)
#define SECU2_IRQ_STAT1_ILL_USART5_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_USART5_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_USART5_SEC_W  SECU2_IRQ_STAT1_ILL_USART5_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_USART5_SEC_R_Pos  (7U)
#define SECU2_IRQ_STAT1_ILL_USART5_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_USART5_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_USART5_SEC_R  SECU2_IRQ_STAT1_ILL_USART5_SEC_R_Msk
#define SECU2_IRQ_STAT1_ILL_PATCH_PRIV_W_Pos  (12U)
#define SECU2_IRQ_STAT1_ILL_PATCH_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PATCH_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_PATCH_PRIV_W  SECU2_IRQ_STAT1_ILL_PATCH_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_PATCH_PRIV_R_Pos  (13U)
#define SECU2_IRQ_STAT1_ILL_PATCH_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PATCH_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_PATCH_PRIV_R  SECU2_IRQ_STAT1_ILL_PATCH_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_PATCH_SEC_W_Pos  (14U)
#define SECU2_IRQ_STAT1_ILL_PATCH_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PATCH_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_PATCH_SEC_W  SECU2_IRQ_STAT1_ILL_PATCH_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_PATCH_SEC_R_Pos  (15U)
#define SECU2_IRQ_STAT1_ILL_PATCH_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PATCH_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_PATCH_SEC_R  SECU2_IRQ_STAT1_ILL_PATCH_SEC_R_Msk
#define SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_W_Pos  (16U)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_W  SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_R_Pos  (17U)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_R  SECU2_IRQ_STAT1_ILL_PINMUX2_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_W_Pos  (18U)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_W  SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_R_Pos  (19U)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_R  SECU2_IRQ_STAT1_ILL_PINMUX2_SEC_R_Msk
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_W_Pos  (20U)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_W  SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_R_Pos  (21U)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_R  SECU2_IRQ_STAT1_ILL_MAILBOX2_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_W_Pos  (22U)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_W  SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_R_Pos  (23U)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_R  SECU2_IRQ_STAT1_ILL_MAILBOX2_SEC_R_Msk
#define SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_W_Pos  (24U)
#define SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_W  SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_R_Pos  (25U)
#define SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_R  SECU2_IRQ_STAT1_ILL_DMAC2_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_DMAC2_SEC_W_Pos  (26U)
#define SECU2_IRQ_STAT1_ILL_DMAC2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_DMAC2_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_DMAC2_SEC_W  SECU2_IRQ_STAT1_ILL_DMAC2_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_DMAC2_SEC_R_Pos  (27U)
#define SECU2_IRQ_STAT1_ILL_DMAC2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_DMAC2_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_DMAC2_SEC_R  SECU2_IRQ_STAT1_ILL_DMAC2_SEC_R_Msk
#define SECU2_IRQ_STAT1_ILL_RCC2_PRIV_W_Pos  (28U)
#define SECU2_IRQ_STAT1_ILL_RCC2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_RCC2_PRIV_W_Pos)
#define SECU2_IRQ_STAT1_ILL_RCC2_PRIV_W  SECU2_IRQ_STAT1_ILL_RCC2_PRIV_W_Msk
#define SECU2_IRQ_STAT1_ILL_RCC2_PRIV_R_Pos  (29U)
#define SECU2_IRQ_STAT1_ILL_RCC2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_RCC2_PRIV_R_Pos)
#define SECU2_IRQ_STAT1_ILL_RCC2_PRIV_R  SECU2_IRQ_STAT1_ILL_RCC2_PRIV_R_Msk
#define SECU2_IRQ_STAT1_ILL_RCC2_SEC_W_Pos  (30U)
#define SECU2_IRQ_STAT1_ILL_RCC2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_RCC2_SEC_W_Pos)
#define SECU2_IRQ_STAT1_ILL_RCC2_SEC_W  SECU2_IRQ_STAT1_ILL_RCC2_SEC_W_Msk
#define SECU2_IRQ_STAT1_ILL_RCC2_SEC_R_Pos  (31U)
#define SECU2_IRQ_STAT1_ILL_RCC2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT1_ILL_RCC2_SEC_R_Pos)
#define SECU2_IRQ_STAT1_ILL_RCC2_SEC_R  SECU2_IRQ_STAT1_ILL_RCC2_SEC_R_Msk

/**************** Bit definition for SECU2_IRQ_STAT2 register *****************/
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_W_Pos  (0U)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_W_Pos)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_W  SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_W_Msk
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_R_Pos  (1U)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_R_Pos)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_R  SECU2_IRQ_STAT2_ILL_SYSCFG2_PRIV_R_Msk
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_W_Pos  (2U)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_W_Pos)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_W  SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_W_Msk
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_R_Pos  (3U)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_R_Pos)
#define SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_R  SECU2_IRQ_STAT2_ILL_SYSCFG2_SEC_R_Msk
#define SECU2_IRQ_STAT2_ILL_PTC2_PRIV_W_Pos  (4U)
#define SECU2_IRQ_STAT2_ILL_PTC2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_PTC2_PRIV_W_Pos)
#define SECU2_IRQ_STAT2_ILL_PTC2_PRIV_W  SECU2_IRQ_STAT2_ILL_PTC2_PRIV_W_Msk
#define SECU2_IRQ_STAT2_ILL_PTC2_PRIV_R_Pos  (5U)
#define SECU2_IRQ_STAT2_ILL_PTC2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_PTC2_PRIV_R_Pos)
#define SECU2_IRQ_STAT2_ILL_PTC2_PRIV_R  SECU2_IRQ_STAT2_ILL_PTC2_PRIV_R_Msk
#define SECU2_IRQ_STAT2_ILL_PTC2_SEC_W_Pos  (6U)
#define SECU2_IRQ_STAT2_ILL_PTC2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_PTC2_SEC_W_Pos)
#define SECU2_IRQ_STAT2_ILL_PTC2_SEC_W  SECU2_IRQ_STAT2_ILL_PTC2_SEC_W_Msk
#define SECU2_IRQ_STAT2_ILL_PTC2_SEC_R_Pos  (7U)
#define SECU2_IRQ_STAT2_ILL_PTC2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_PTC2_SEC_R_Pos)
#define SECU2_IRQ_STAT2_ILL_PTC2_SEC_R  SECU2_IRQ_STAT2_ILL_PTC2_SEC_R_Msk
#define SECU2_IRQ_STAT2_ILL_WDT2_PRIV_W_Pos  (8U)
#define SECU2_IRQ_STAT2_ILL_WDT2_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_WDT2_PRIV_W_Pos)
#define SECU2_IRQ_STAT2_ILL_WDT2_PRIV_W  SECU2_IRQ_STAT2_ILL_WDT2_PRIV_W_Msk
#define SECU2_IRQ_STAT2_ILL_WDT2_PRIV_R_Pos  (9U)
#define SECU2_IRQ_STAT2_ILL_WDT2_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_WDT2_PRIV_R_Pos)
#define SECU2_IRQ_STAT2_ILL_WDT2_PRIV_R  SECU2_IRQ_STAT2_ILL_WDT2_PRIV_R_Msk
#define SECU2_IRQ_STAT2_ILL_WDT2_SEC_W_Pos  (10U)
#define SECU2_IRQ_STAT2_ILL_WDT2_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_WDT2_SEC_W_Pos)
#define SECU2_IRQ_STAT2_ILL_WDT2_SEC_W  SECU2_IRQ_STAT2_ILL_WDT2_SEC_W_Msk
#define SECU2_IRQ_STAT2_ILL_WDT2_SEC_R_Pos  (11U)
#define SECU2_IRQ_STAT2_ILL_WDT2_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_WDT2_SEC_R_Pos)
#define SECU2_IRQ_STAT2_ILL_WDT2_SEC_R  SECU2_IRQ_STAT2_ILL_WDT2_SEC_R_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_W_Pos  (12U)
#define SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_W_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_W  SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_W_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_R_Pos  (13U)
#define SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_R_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_R  SECU2_IRQ_STAT2_ILL_BTIM4_PRIV_R_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM4_SEC_W_Pos  (14U)
#define SECU2_IRQ_STAT2_ILL_BTIM4_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM4_SEC_W_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM4_SEC_W  SECU2_IRQ_STAT2_ILL_BTIM4_SEC_W_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM4_SEC_R_Pos  (15U)
#define SECU2_IRQ_STAT2_ILL_BTIM4_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM4_SEC_R_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM4_SEC_R  SECU2_IRQ_STAT2_ILL_BTIM4_SEC_R_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_W_Pos  (16U)
#define SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_W_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_W  SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_W_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_R_Pos  (17U)
#define SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_R_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_R  SECU2_IRQ_STAT2_ILL_BTIM3_PRIV_R_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM3_SEC_W_Pos  (18U)
#define SECU2_IRQ_STAT2_ILL_BTIM3_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM3_SEC_W_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM3_SEC_W  SECU2_IRQ_STAT2_ILL_BTIM3_SEC_W_Msk
#define SECU2_IRQ_STAT2_ILL_BTIM3_SEC_R_Pos  (19U)
#define SECU2_IRQ_STAT2_ILL_BTIM3_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_BTIM3_SEC_R_Pos)
#define SECU2_IRQ_STAT2_ILL_BTIM3_SEC_R  SECU2_IRQ_STAT2_ILL_BTIM3_SEC_R_Msk
#define SECU2_IRQ_STAT2_ILL_AON_PRIV_W_Pos  (20U)
#define SECU2_IRQ_STAT2_ILL_AON_PRIV_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_AON_PRIV_W_Pos)
#define SECU2_IRQ_STAT2_ILL_AON_PRIV_W  SECU2_IRQ_STAT2_ILL_AON_PRIV_W_Msk
#define SECU2_IRQ_STAT2_ILL_AON_PRIV_R_Pos  (21U)
#define SECU2_IRQ_STAT2_ILL_AON_PRIV_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_AON_PRIV_R_Pos)
#define SECU2_IRQ_STAT2_ILL_AON_PRIV_R  SECU2_IRQ_STAT2_ILL_AON_PRIV_R_Msk
#define SECU2_IRQ_STAT2_ILL_AON_SEC_W_Pos  (22U)
#define SECU2_IRQ_STAT2_ILL_AON_SEC_W_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_AON_SEC_W_Pos)
#define SECU2_IRQ_STAT2_ILL_AON_SEC_W   SECU2_IRQ_STAT2_ILL_AON_SEC_W_Msk
#define SECU2_IRQ_STAT2_ILL_AON_SEC_R_Pos  (23U)
#define SECU2_IRQ_STAT2_ILL_AON_SEC_R_Msk  (0x1UL << SECU2_IRQ_STAT2_ILL_AON_SEC_R_Pos)
#define SECU2_IRQ_STAT2_ILL_AON_SEC_R   SECU2_IRQ_STAT2_ILL_AON_SEC_R_Msk

/***************** Bit definition for SECU2_IRQ_CFG0 register *****************/
#define SECU2_IRQ_CFG0_ILL_RAM0_PRIV_W_MASK_Pos  (0U)
#define SECU2_IRQ_CFG0_ILL_RAM0_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM0_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM0_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_RAM0_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM0_PRIV_R_MASK_Pos  (1U)
#define SECU2_IRQ_CFG0_ILL_RAM0_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM0_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM0_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_RAM0_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM0_SEC_W_MASK_Pos  (2U)
#define SECU2_IRQ_CFG0_ILL_RAM0_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM0_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM0_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_RAM0_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM0_SEC_R_MASK_Pos  (3U)
#define SECU2_IRQ_CFG0_ILL_RAM0_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM0_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM0_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_RAM0_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM1_PRIV_W_MASK_Pos  (4U)
#define SECU2_IRQ_CFG0_ILL_RAM1_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM1_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM1_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_RAM1_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM1_PRIV_R_MASK_Pos  (5U)
#define SECU2_IRQ_CFG0_ILL_RAM1_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM1_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM1_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_RAM1_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM1_SEC_W_MASK_Pos  (6U)
#define SECU2_IRQ_CFG0_ILL_RAM1_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM1_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM1_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_RAM1_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RAM1_SEC_R_MASK_Pos  (7U)
#define SECU2_IRQ_CFG0_ILL_RAM1_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RAM1_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RAM1_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_RAM1_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_CRC2_PRIV_W_MASK_Pos  (8U)
#define SECU2_IRQ_CFG0_ILL_CRC2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_CRC2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_CRC2_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_CRC2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_CRC2_PRIV_R_MASK_Pos  (9U)
#define SECU2_IRQ_CFG0_ILL_CRC2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_CRC2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_CRC2_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_CRC2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_CRC2_SEC_W_MASK_Pos  (10U)
#define SECU2_IRQ_CFG0_ILL_CRC2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_CRC2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_CRC2_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_CRC2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_CRC2_SEC_R_MASK_Pos  (11U)
#define SECU2_IRQ_CFG0_ILL_CRC2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_CRC2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_CRC2_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_CRC2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_W_MASK_Pos  (12U)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_R_MASK_Pos  (13U)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_BT_MAC_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_W_MASK_Pos  (14U)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_R_MASK_Pos  (15U)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_BT_MAC_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_W_MASK_Pos  (16U)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_R_MASK_Pos  (17U)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_BT_PHY_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_W_MASK_Pos  (18U)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_R_MASK_Pos  (19U)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_BT_PHY_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RFC_PRIV_W_MASK_Pos  (20U)
#define SECU2_IRQ_CFG0_ILL_RFC_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RFC_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RFC_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_RFC_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RFC_PRIV_R_MASK_Pos  (21U)
#define SECU2_IRQ_CFG0_ILL_RFC_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RFC_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RFC_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_RFC_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RFC_SEC_W_MASK_Pos  (22U)
#define SECU2_IRQ_CFG0_ILL_RFC_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RFC_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RFC_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_RFC_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_RFC_SEC_R_MASK_Pos  (23U)
#define SECU2_IRQ_CFG0_ILL_RFC_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_RFC_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_RFC_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_RFC_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_W_MASK_Pos  (24U)
#define SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_W_MASK  SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_R_MASK_Pos  (25U)
#define SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_R_MASK  SECU2_IRQ_CFG0_ILL_GPIO2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_GPIO2_SEC_W_MASK_Pos  (26U)
#define SECU2_IRQ_CFG0_ILL_GPIO2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_GPIO2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_GPIO2_SEC_W_MASK  SECU2_IRQ_CFG0_ILL_GPIO2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG0_ILL_GPIO2_SEC_R_MASK_Pos  (27U)
#define SECU2_IRQ_CFG0_ILL_GPIO2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG0_ILL_GPIO2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG0_ILL_GPIO2_SEC_R_MASK  SECU2_IRQ_CFG0_ILL_GPIO2_SEC_R_MASK_Msk

/***************** Bit definition for SECU2_IRQ_CFG1 register *****************/
#define SECU2_IRQ_CFG1_ILL_SECU2_PRIV_W_MASK_Pos  (0U)
#define SECU2_IRQ_CFG1_ILL_SECU2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_SECU2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_SECU2_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_SECU2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_SECU2_PRIV_R_MASK_Pos  (1U)
#define SECU2_IRQ_CFG1_ILL_SECU2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_SECU2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_SECU2_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_SECU2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_SECU2_SEC_W_MASK_Pos  (2U)
#define SECU2_IRQ_CFG1_ILL_SECU2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_SECU2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_SECU2_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_SECU2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_SECU2_SEC_R_MASK_Pos  (3U)
#define SECU2_IRQ_CFG1_ILL_SECU2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_SECU2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_SECU2_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_SECU2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_USART5_PRIV_W_MASK_Pos  (4U)
#define SECU2_IRQ_CFG1_ILL_USART5_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_USART5_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_USART5_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_USART5_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_USART5_PRIV_R_MASK_Pos  (5U)
#define SECU2_IRQ_CFG1_ILL_USART5_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_USART5_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_USART5_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_USART5_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_USART5_SEC_W_MASK_Pos  (6U)
#define SECU2_IRQ_CFG1_ILL_USART5_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_USART5_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_USART5_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_USART5_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_USART5_SEC_R_MASK_Pos  (7U)
#define SECU2_IRQ_CFG1_ILL_USART5_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_USART5_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_USART5_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_USART5_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PATCH_PRIV_W_MASK_Pos  (12U)
#define SECU2_IRQ_CFG1_ILL_PATCH_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PATCH_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PATCH_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_PATCH_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PATCH_PRIV_R_MASK_Pos  (13U)
#define SECU2_IRQ_CFG1_ILL_PATCH_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PATCH_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PATCH_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_PATCH_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PATCH_SEC_W_MASK_Pos  (14U)
#define SECU2_IRQ_CFG1_ILL_PATCH_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PATCH_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PATCH_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_PATCH_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PATCH_SEC_R_MASK_Pos  (15U)
#define SECU2_IRQ_CFG1_ILL_PATCH_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PATCH_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PATCH_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_PATCH_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_W_MASK_Pos  (16U)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_R_MASK_Pos  (17U)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_PINMUX2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_W_MASK_Pos  (18U)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_R_MASK_Pos  (19U)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_PINMUX2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_W_MASK_Pos  (20U)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_R_MASK_Pos  (21U)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_MAILBOX2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_W_MASK_Pos  (22U)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_R_MASK_Pos  (23U)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_MAILBOX2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_W_MASK_Pos  (24U)
#define SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_R_MASK_Pos  (25U)
#define SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_DMAC2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_DMAC2_SEC_W_MASK_Pos  (26U)
#define SECU2_IRQ_CFG1_ILL_DMAC2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_DMAC2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_DMAC2_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_DMAC2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_DMAC2_SEC_R_MASK_Pos  (27U)
#define SECU2_IRQ_CFG1_ILL_DMAC2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_DMAC2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_DMAC2_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_DMAC2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_RCC2_PRIV_W_MASK_Pos  (28U)
#define SECU2_IRQ_CFG1_ILL_RCC2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_RCC2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_RCC2_PRIV_W_MASK  SECU2_IRQ_CFG1_ILL_RCC2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_RCC2_PRIV_R_MASK_Pos  (29U)
#define SECU2_IRQ_CFG1_ILL_RCC2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_RCC2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_RCC2_PRIV_R_MASK  SECU2_IRQ_CFG1_ILL_RCC2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_RCC2_SEC_W_MASK_Pos  (30U)
#define SECU2_IRQ_CFG1_ILL_RCC2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_RCC2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_RCC2_SEC_W_MASK  SECU2_IRQ_CFG1_ILL_RCC2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG1_ILL_RCC2_SEC_R_MASK_Pos  (31U)
#define SECU2_IRQ_CFG1_ILL_RCC2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG1_ILL_RCC2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG1_ILL_RCC2_SEC_R_MASK  SECU2_IRQ_CFG1_ILL_RCC2_SEC_R_MASK_Msk

/***************** Bit definition for SECU2_IRQ_CFG2 register *****************/
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_W_MASK_Pos  (0U)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_W_MASK  SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_R_MASK_Pos  (1U)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_R_MASK  SECU2_IRQ_CFG2_ILL_SYSCFG2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_W_MASK_Pos  (2U)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_W_MASK  SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_R_MASK_Pos  (3U)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_R_MASK  SECU2_IRQ_CFG2_ILL_SYSCFG2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_PTC2_PRIV_W_MASK_Pos  (4U)
#define SECU2_IRQ_CFG2_ILL_PTC2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_PTC2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_PTC2_PRIV_W_MASK  SECU2_IRQ_CFG2_ILL_PTC2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_PTC2_PRIV_R_MASK_Pos  (5U)
#define SECU2_IRQ_CFG2_ILL_PTC2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_PTC2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_PTC2_PRIV_R_MASK  SECU2_IRQ_CFG2_ILL_PTC2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_PTC2_SEC_W_MASK_Pos  (6U)
#define SECU2_IRQ_CFG2_ILL_PTC2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_PTC2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_PTC2_SEC_W_MASK  SECU2_IRQ_CFG2_ILL_PTC2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_PTC2_SEC_R_MASK_Pos  (7U)
#define SECU2_IRQ_CFG2_ILL_PTC2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_PTC2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_PTC2_SEC_R_MASK  SECU2_IRQ_CFG2_ILL_PTC2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_WDT2_PRIV_W_MASK_Pos  (8U)
#define SECU2_IRQ_CFG2_ILL_WDT2_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_WDT2_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_WDT2_PRIV_W_MASK  SECU2_IRQ_CFG2_ILL_WDT2_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_WDT2_PRIV_R_MASK_Pos  (9U)
#define SECU2_IRQ_CFG2_ILL_WDT2_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_WDT2_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_WDT2_PRIV_R_MASK  SECU2_IRQ_CFG2_ILL_WDT2_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_WDT2_SEC_W_MASK_Pos  (10U)
#define SECU2_IRQ_CFG2_ILL_WDT2_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_WDT2_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_WDT2_SEC_W_MASK  SECU2_IRQ_CFG2_ILL_WDT2_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_WDT2_SEC_R_MASK_Pos  (11U)
#define SECU2_IRQ_CFG2_ILL_WDT2_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_WDT2_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_WDT2_SEC_R_MASK  SECU2_IRQ_CFG2_ILL_WDT2_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_W_MASK_Pos  (12U)
#define SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_W_MASK  SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_R_MASK_Pos  (13U)
#define SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_R_MASK  SECU2_IRQ_CFG2_ILL_BTIM4_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM4_SEC_W_MASK_Pos  (14U)
#define SECU2_IRQ_CFG2_ILL_BTIM4_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM4_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM4_SEC_W_MASK  SECU2_IRQ_CFG2_ILL_BTIM4_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM4_SEC_R_MASK_Pos  (15U)
#define SECU2_IRQ_CFG2_ILL_BTIM4_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM4_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM4_SEC_R_MASK  SECU2_IRQ_CFG2_ILL_BTIM4_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_W_MASK_Pos  (16U)
#define SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_W_MASK  SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_R_MASK_Pos  (17U)
#define SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_R_MASK  SECU2_IRQ_CFG2_ILL_BTIM3_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM3_SEC_W_MASK_Pos  (18U)
#define SECU2_IRQ_CFG2_ILL_BTIM3_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM3_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM3_SEC_W_MASK  SECU2_IRQ_CFG2_ILL_BTIM3_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_BTIM3_SEC_R_MASK_Pos  (19U)
#define SECU2_IRQ_CFG2_ILL_BTIM3_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_BTIM3_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_BTIM3_SEC_R_MASK  SECU2_IRQ_CFG2_ILL_BTIM3_SEC_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_AON_PRIV_W_MASK_Pos  (20U)
#define SECU2_IRQ_CFG2_ILL_AON_PRIV_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_AON_PRIV_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_AON_PRIV_W_MASK  SECU2_IRQ_CFG2_ILL_AON_PRIV_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_AON_PRIV_R_MASK_Pos  (21U)
#define SECU2_IRQ_CFG2_ILL_AON_PRIV_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_AON_PRIV_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_AON_PRIV_R_MASK  SECU2_IRQ_CFG2_ILL_AON_PRIV_R_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_AON_SEC_W_MASK_Pos  (22U)
#define SECU2_IRQ_CFG2_ILL_AON_SEC_W_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_AON_SEC_W_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_AON_SEC_W_MASK  SECU2_IRQ_CFG2_ILL_AON_SEC_W_MASK_Msk
#define SECU2_IRQ_CFG2_ILL_AON_SEC_R_MASK_Pos  (23U)
#define SECU2_IRQ_CFG2_ILL_AON_SEC_R_MASK_Msk  (0x1UL << SECU2_IRQ_CFG2_ILL_AON_SEC_R_MASK_Pos)
#define SECU2_IRQ_CFG2_ILL_AON_SEC_R_MASK  SECU2_IRQ_CFG2_ILL_AON_SEC_R_MASK_Msk

/************** Bit definition for SECU2_LPMST_ATTR_CFG register **************/
#define SECU2_LPMST_ATTR_CFG_DMAC2_SEC_Pos  (4U)
#define SECU2_LPMST_ATTR_CFG_DMAC2_SEC_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_DMAC2_SEC_Pos)
#define SECU2_LPMST_ATTR_CFG_DMAC2_SEC  SECU2_LPMST_ATTR_CFG_DMAC2_SEC_Msk
#define SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_Pos  (5U)
#define SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_Pos)
#define SECU2_LPMST_ATTR_CFG_DMAC2_PRIV  SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_Msk
#define SECU2_LPMST_ATTR_CFG_DMAC2_SEC_USE_Pos  (6U)
#define SECU2_LPMST_ATTR_CFG_DMAC2_SEC_USE_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_DMAC2_SEC_USE_Pos)
#define SECU2_LPMST_ATTR_CFG_DMAC2_SEC_USE  SECU2_LPMST_ATTR_CFG_DMAC2_SEC_USE_Msk
#define SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_USE_Pos  (7U)
#define SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_USE_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_USE_Pos)
#define SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_USE  SECU2_LPMST_ATTR_CFG_DMAC2_PRIV_USE_Msk
#define SECU2_LPMST_ATTR_CFG_PTC2_SEC_Pos  (8U)
#define SECU2_LPMST_ATTR_CFG_PTC2_SEC_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_PTC2_SEC_Pos)
#define SECU2_LPMST_ATTR_CFG_PTC2_SEC   SECU2_LPMST_ATTR_CFG_PTC2_SEC_Msk
#define SECU2_LPMST_ATTR_CFG_PTC2_PRIV_Pos  (9U)
#define SECU2_LPMST_ATTR_CFG_PTC2_PRIV_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_PTC2_PRIV_Pos)
#define SECU2_LPMST_ATTR_CFG_PTC2_PRIV  SECU2_LPMST_ATTR_CFG_PTC2_PRIV_Msk
#define SECU2_LPMST_ATTR_CFG_PTC2_SEC_USE_Pos  (10U)
#define SECU2_LPMST_ATTR_CFG_PTC2_SEC_USE_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_PTC2_SEC_USE_Pos)
#define SECU2_LPMST_ATTR_CFG_PTC2_SEC_USE  SECU2_LPMST_ATTR_CFG_PTC2_SEC_USE_Msk
#define SECU2_LPMST_ATTR_CFG_PTC2_PRIV_USE_Pos  (11U)
#define SECU2_LPMST_ATTR_CFG_PTC2_PRIV_USE_Msk  (0x1UL << SECU2_LPMST_ATTR_CFG_PTC2_PRIV_USE_Pos)
#define SECU2_LPMST_ATTR_CFG_PTC2_PRIV_USE  SECU2_LPMST_ATTR_CFG_PTC2_PRIV_USE_Msk

/************* Bit definition for SECU2_LPSLV_ATTR_CFG0 register **************/
#define SECU2_LPSLV_ATTR_CFG0_CRC2_SEC_Pos  (0U)
#define SECU2_LPSLV_ATTR_CFG0_CRC2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_CRC2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG0_CRC2_SEC  SECU2_LPSLV_ATTR_CFG0_CRC2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG0_CRC2_PRIV_Pos  (1U)
#define SECU2_LPSLV_ATTR_CFG0_CRC2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_CRC2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG0_CRC2_PRIV  SECU2_LPSLV_ATTR_CFG0_CRC2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG0_BT_MAC_SEC_Pos  (2U)
#define SECU2_LPSLV_ATTR_CFG0_BT_MAC_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_BT_MAC_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG0_BT_MAC_SEC  SECU2_LPSLV_ATTR_CFG0_BT_MAC_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG0_BT_MAC_PRIV_Pos  (3U)
#define SECU2_LPSLV_ATTR_CFG0_BT_MAC_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_BT_MAC_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG0_BT_MAC_PRIV  SECU2_LPSLV_ATTR_CFG0_BT_MAC_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG0_BT_PHY_SEC_Pos  (4U)
#define SECU2_LPSLV_ATTR_CFG0_BT_PHY_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_BT_PHY_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG0_BT_PHY_SEC  SECU2_LPSLV_ATTR_CFG0_BT_PHY_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG0_BT_PHY_PRIV_Pos  (5U)
#define SECU2_LPSLV_ATTR_CFG0_BT_PHY_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_BT_PHY_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG0_BT_PHY_PRIV  SECU2_LPSLV_ATTR_CFG0_BT_PHY_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG0_RFC_SEC_Pos  (6U)
#define SECU2_LPSLV_ATTR_CFG0_RFC_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_RFC_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG0_RFC_SEC   SECU2_LPSLV_ATTR_CFG0_RFC_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG0_RFC_PRIV_Pos  (7U)
#define SECU2_LPSLV_ATTR_CFG0_RFC_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_RFC_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG0_RFC_PRIV  SECU2_LPSLV_ATTR_CFG0_RFC_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG0_GPIO2_SEC_Pos  (8U)
#define SECU2_LPSLV_ATTR_CFG0_GPIO2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_GPIO2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG0_GPIO2_SEC  SECU2_LPSLV_ATTR_CFG0_GPIO2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG0_GPIO2_PRIV_Pos  (9U)
#define SECU2_LPSLV_ATTR_CFG0_GPIO2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_GPIO2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG0_GPIO2_PRIV  SECU2_LPSLV_ATTR_CFG0_GPIO2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG0_AON_SEC_Pos  (10U)
#define SECU2_LPSLV_ATTR_CFG0_AON_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_AON_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG0_AON_SEC   SECU2_LPSLV_ATTR_CFG0_AON_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG0_AON_PRIV_Pos  (11U)
#define SECU2_LPSLV_ATTR_CFG0_AON_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG0_AON_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG0_AON_PRIV  SECU2_LPSLV_ATTR_CFG0_AON_PRIV_Msk

/************* Bit definition for SECU2_LPSLV_ATTR_CFG1 register **************/
#define SECU2_LPSLV_ATTR_CFG1_SYSCFG2_SEC_Pos  (0U)
#define SECU2_LPSLV_ATTR_CFG1_SYSCFG2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_SYSCFG2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_SYSCFG2_SEC  SECU2_LPSLV_ATTR_CFG1_SYSCFG2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_SYSCFG2_PRIV_Pos  (1U)
#define SECU2_LPSLV_ATTR_CFG1_SYSCFG2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_SYSCFG2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_SYSCFG2_PRIV  SECU2_LPSLV_ATTR_CFG1_SYSCFG2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_PTC2_SEC_Pos  (2U)
#define SECU2_LPSLV_ATTR_CFG1_PTC2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_PTC2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_PTC2_SEC  SECU2_LPSLV_ATTR_CFG1_PTC2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_PTC2_PRIV_Pos  (3U)
#define SECU2_LPSLV_ATTR_CFG1_PTC2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_PTC2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_PTC2_PRIV  SECU2_LPSLV_ATTR_CFG1_PTC2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_WDT2_SEC_Pos  (4U)
#define SECU2_LPSLV_ATTR_CFG1_WDT2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_WDT2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_WDT2_SEC  SECU2_LPSLV_ATTR_CFG1_WDT2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_WDT2_PRIV_Pos  (5U)
#define SECU2_LPSLV_ATTR_CFG1_WDT2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_WDT2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_WDT2_PRIV  SECU2_LPSLV_ATTR_CFG1_WDT2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_BTIM4_SEC_Pos  (6U)
#define SECU2_LPSLV_ATTR_CFG1_BTIM4_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_BTIM4_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_BTIM4_SEC  SECU2_LPSLV_ATTR_CFG1_BTIM4_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_BTIM4_PRIV_Pos  (7U)
#define SECU2_LPSLV_ATTR_CFG1_BTIM4_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_BTIM4_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_BTIM4_PRIV  SECU2_LPSLV_ATTR_CFG1_BTIM4_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_BTIM3_SEC_Pos  (8U)
#define SECU2_LPSLV_ATTR_CFG1_BTIM3_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_BTIM3_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_BTIM3_SEC  SECU2_LPSLV_ATTR_CFG1_BTIM3_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_BTIM3_PRIV_Pos  (9U)
#define SECU2_LPSLV_ATTR_CFG1_BTIM3_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_BTIM3_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_BTIM3_PRIV  SECU2_LPSLV_ATTR_CFG1_BTIM3_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_USART5_SEC_Pos  (10U)
#define SECU2_LPSLV_ATTR_CFG1_USART5_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_USART5_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_USART5_SEC  SECU2_LPSLV_ATTR_CFG1_USART5_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_USART5_PRIV_Pos  (11U)
#define SECU2_LPSLV_ATTR_CFG1_USART5_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_USART5_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_USART5_PRIV  SECU2_LPSLV_ATTR_CFG1_USART5_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_PATCH_SEC_Pos  (14U)
#define SECU2_LPSLV_ATTR_CFG1_PATCH_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_PATCH_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_PATCH_SEC  SECU2_LPSLV_ATTR_CFG1_PATCH_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_PATCH_PRIV_Pos  (15U)
#define SECU2_LPSLV_ATTR_CFG1_PATCH_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_PATCH_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_PATCH_PRIV  SECU2_LPSLV_ATTR_CFG1_PATCH_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_PINMUX2_SEC_Pos  (16U)
#define SECU2_LPSLV_ATTR_CFG1_PINMUX2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_PINMUX2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_PINMUX2_SEC  SECU2_LPSLV_ATTR_CFG1_PINMUX2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_PINMUX2_PRIV_Pos  (17U)
#define SECU2_LPSLV_ATTR_CFG1_PINMUX2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_PINMUX2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_PINMUX2_PRIV  SECU2_LPSLV_ATTR_CFG1_PINMUX2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_MAILBOX2_SEC_Pos  (18U)
#define SECU2_LPSLV_ATTR_CFG1_MAILBOX2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_MAILBOX2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_MAILBOX2_SEC  SECU2_LPSLV_ATTR_CFG1_MAILBOX2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_MAILBOX2_PRIV_Pos  (19U)
#define SECU2_LPSLV_ATTR_CFG1_MAILBOX2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_MAILBOX2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_MAILBOX2_PRIV  SECU2_LPSLV_ATTR_CFG1_MAILBOX2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_DMAC2_SEC_Pos  (20U)
#define SECU2_LPSLV_ATTR_CFG1_DMAC2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_DMAC2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_DMAC2_SEC  SECU2_LPSLV_ATTR_CFG1_DMAC2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_DMAC2_PRIV_Pos  (21U)
#define SECU2_LPSLV_ATTR_CFG1_DMAC2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_DMAC2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_DMAC2_PRIV  SECU2_LPSLV_ATTR_CFG1_DMAC2_PRIV_Msk
#define SECU2_LPSLV_ATTR_CFG1_RCC2_SEC_Pos  (22U)
#define SECU2_LPSLV_ATTR_CFG1_RCC2_SEC_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_RCC2_SEC_Pos)
#define SECU2_LPSLV_ATTR_CFG1_RCC2_SEC  SECU2_LPSLV_ATTR_CFG1_RCC2_SEC_Msk
#define SECU2_LPSLV_ATTR_CFG1_RCC2_PRIV_Pos  (23U)
#define SECU2_LPSLV_ATTR_CFG1_RCC2_PRIV_Msk  (0x1UL << SECU2_LPSLV_ATTR_CFG1_RCC2_PRIV_Pos)
#define SECU2_LPSLV_ATTR_CFG1_RCC2_PRIV  SECU2_LPSLV_ATTR_CFG1_RCC2_PRIV_Msk

/*************** Bit definition for SECU2_RAM0_R0_CFG0 register ***************/
#define SECU2_RAM0_R0_CFG0_ST_ADDR_Pos  (2U)
#define SECU2_RAM0_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM0_R0_CFG0_ST_ADDR_Pos)
#define SECU2_RAM0_R0_CFG0_ST_ADDR      SECU2_RAM0_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU2_RAM0_R0_CFG1 register ***************/
#define SECU2_RAM0_R0_CFG1_END_ADDR_Pos  (2U)
#define SECU2_RAM0_R0_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM0_R0_CFG1_END_ADDR_Pos)
#define SECU2_RAM0_R0_CFG1_END_ADDR     SECU2_RAM0_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU2_RAM0_R1_CFG0 register ***************/
#define SECU2_RAM0_R1_CFG0_ST_ADDR_Pos  (2U)
#define SECU2_RAM0_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM0_R1_CFG0_ST_ADDR_Pos)
#define SECU2_RAM0_R1_CFG0_ST_ADDR      SECU2_RAM0_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU2_RAM0_R1_CFG1 register ***************/
#define SECU2_RAM0_R1_CFG1_END_ADDR_Pos  (2U)
#define SECU2_RAM0_R1_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM0_R1_CFG1_END_ADDR_Pos)
#define SECU2_RAM0_R1_CFG1_END_ADDR     SECU2_RAM0_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU2_RAM0_RW_CFG register ****************/
#define SECU2_RAM0_RW_CFG_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU2_RAM0_RW_CFG_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R0_PRIV_WR_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R0_PRIV_WR_ATTR  SECU2_RAM0_RW_CFG_R0_PRIV_WR_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU2_RAM0_RW_CFG_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R0_PRIV_RD_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R0_PRIV_RD_ATTR  SECU2_RAM0_RW_CFG_R0_PRIV_RD_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU2_RAM0_RW_CFG_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R0_SEC_WR_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R0_SEC_WR_ATTR  SECU2_RAM0_RW_CFG_R0_SEC_WR_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU2_RAM0_RW_CFG_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R0_SEC_RD_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R0_SEC_RD_ATTR  SECU2_RAM0_RW_CFG_R0_SEC_RD_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU2_RAM0_RW_CFG_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R1_PRIV_WR_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R1_PRIV_WR_ATTR  SECU2_RAM0_RW_CFG_R1_PRIV_WR_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU2_RAM0_RW_CFG_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R1_PRIV_RD_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R1_PRIV_RD_ATTR  SECU2_RAM0_RW_CFG_R1_PRIV_RD_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU2_RAM0_RW_CFG_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R1_SEC_WR_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R1_SEC_WR_ATTR  SECU2_RAM0_RW_CFG_R1_SEC_WR_ATTR_Msk
#define SECU2_RAM0_RW_CFG_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU2_RAM0_RW_CFG_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU2_RAM0_RW_CFG_R1_SEC_RD_ATTR_Pos)
#define SECU2_RAM0_RW_CFG_R1_SEC_RD_ATTR  SECU2_RAM0_RW_CFG_R1_SEC_RD_ATTR_Msk

/*************** Bit definition for SECU2_RAM1_R0_CFG0 register ***************/
#define SECU2_RAM1_R0_CFG0_ST_ADDR_Pos  (2U)
#define SECU2_RAM1_R0_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM1_R0_CFG0_ST_ADDR_Pos)
#define SECU2_RAM1_R0_CFG0_ST_ADDR      SECU2_RAM1_R0_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU2_RAM1_R0_CFG1 register ***************/
#define SECU2_RAM1_R0_CFG1_END_ADDR_Pos  (2U)
#define SECU2_RAM1_R0_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM1_R0_CFG1_END_ADDR_Pos)
#define SECU2_RAM1_R0_CFG1_END_ADDR     SECU2_RAM1_R0_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU2_RAM1_R1_CFG0 register ***************/
#define SECU2_RAM1_R1_CFG0_ST_ADDR_Pos  (2U)
#define SECU2_RAM1_R1_CFG0_ST_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM1_R1_CFG0_ST_ADDR_Pos)
#define SECU2_RAM1_R1_CFG0_ST_ADDR      SECU2_RAM1_R1_CFG0_ST_ADDR_Msk

/*************** Bit definition for SECU2_RAM1_R1_CFG1 register ***************/
#define SECU2_RAM1_R1_CFG1_END_ADDR_Pos  (2U)
#define SECU2_RAM1_R1_CFG1_END_ADDR_Msk  (0x3FFFFFFFUL << SECU2_RAM1_R1_CFG1_END_ADDR_Pos)
#define SECU2_RAM1_R1_CFG1_END_ADDR     SECU2_RAM1_R1_CFG1_END_ADDR_Msk

/*************** Bit definition for SECU2_RAM1_RW_CFG register ****************/
#define SECU2_RAM1_RW_CFG_R0_PRIV_WR_ATTR_Pos  (0U)
#define SECU2_RAM1_RW_CFG_R0_PRIV_WR_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R0_PRIV_WR_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R0_PRIV_WR_ATTR  SECU2_RAM1_RW_CFG_R0_PRIV_WR_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R0_PRIV_RD_ATTR_Pos  (1U)
#define SECU2_RAM1_RW_CFG_R0_PRIV_RD_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R0_PRIV_RD_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R0_PRIV_RD_ATTR  SECU2_RAM1_RW_CFG_R0_PRIV_RD_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R0_SEC_WR_ATTR_Pos  (2U)
#define SECU2_RAM1_RW_CFG_R0_SEC_WR_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R0_SEC_WR_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R0_SEC_WR_ATTR  SECU2_RAM1_RW_CFG_R0_SEC_WR_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R0_SEC_RD_ATTR_Pos  (3U)
#define SECU2_RAM1_RW_CFG_R0_SEC_RD_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R0_SEC_RD_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R0_SEC_RD_ATTR  SECU2_RAM1_RW_CFG_R0_SEC_RD_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R1_PRIV_WR_ATTR_Pos  (4U)
#define SECU2_RAM1_RW_CFG_R1_PRIV_WR_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R1_PRIV_WR_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R1_PRIV_WR_ATTR  SECU2_RAM1_RW_CFG_R1_PRIV_WR_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R1_PRIV_RD_ATTR_Pos  (5U)
#define SECU2_RAM1_RW_CFG_R1_PRIV_RD_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R1_PRIV_RD_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R1_PRIV_RD_ATTR  SECU2_RAM1_RW_CFG_R1_PRIV_RD_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R1_SEC_WR_ATTR_Pos  (6U)
#define SECU2_RAM1_RW_CFG_R1_SEC_WR_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R1_SEC_WR_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R1_SEC_WR_ATTR  SECU2_RAM1_RW_CFG_R1_SEC_WR_ATTR_Msk
#define SECU2_RAM1_RW_CFG_R1_SEC_RD_ATTR_Pos  (7U)
#define SECU2_RAM1_RW_CFG_R1_SEC_RD_ATTR_Msk  (0x1UL << SECU2_RAM1_RW_CFG_R1_SEC_RD_ATTR_Pos)
#define SECU2_RAM1_RW_CFG_R1_SEC_RD_ATTR  SECU2_RAM1_RW_CFG_R1_SEC_RD_ATTR_Msk

#endif
